### ISSUE TITLE
BE - Error Handling Using Async

### ISSUE THREAD

**Issue by danielanatolie** [davidislam/DDS#12]
**Goal**
Use Promises (Async/Await) to send helpful responses to the client.

**Instructions**
1. Currently, there are timing issues when catching errors.
2. Use Async/Await and proper try-catch approaches to send accurate errors back to client.
3. FE should display correct HTTP error code in the browser's developer console log.

**Proof**
Attach a screenshot of Chrome's console.log displaying database error.

**Comment by davidislam** [comment]
cdbe93d9f42df4c2ce20fee5850eb281375902f5
