### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by danielanatolie** [davidislam/DDS#4]
**Goal**
Connect the PostgresSQL database to the nodeJS backend server.

**Instructions**
1. Create a .sql make file that creates a Text database table in our single sql database.
2. Install and use Postman to send a request to the running nodeJS server
3. Ensure that a simple Text entry table can be made
4. The Text table can follow a format similar to:
ID (created by database) | Text (255 characters for example) | createdAt | LastEdit | URL

**Proof**
Attach a screen shot of a Postman request getting a successful response with code 200 after creating a single database entry in the Text table.

**Comment by DavidAnatolie** [comment]
What kind of request should I send to the nodeJS server? And should I create a single database entry in app.js or is it created by the request i.e. should the server handle the request by creating a database entry?

**Comment by danielanatolie** [comment]
You will need to send a POST request through Postman that'll hit an endpoint within node.js, causing a database entry to be made.

**Comment by davidislam** [comment]
<img width="1392" alt="Screen Shot 2020-06-06 at 8 51 49 PM" src="https://user-images.githubusercontent.com/18288490/83959936-a4d03e80-a837-11ea-8f53-4a324f0ca9f3.png">

#4 The purpose of this ticket was to connect the database to the backend server. I did this by using express node.js with node-postgres and postgres.app with postico. I tested it using Postman by making a post request to `/api/text` entry point. Then I checked the db in postico and saw the new record in the `messages` table, as wanted.
